
name: "SilverBullet"
version: "1.0.0"
slug: "silverbullet"
description: "SilverBullet Knowledge System Add-on"
arch:
  - aarch64
startup: application
webui: "http://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3000
map:
  - config:rw
options:
  space_path: "/config/silverbullet-space"
schema:
  space_path: "str"
